# .github/workflows/test-artifacts.yml
name: Test Artifacts

on: workflow_dispatch

jobs:
  test-artifacts-local:
    name: Test Artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - run: echo hello > ./world.txt

      - uses: actions/upload-artifact@v3
        with:
          name: test-artifact
          path: ./world.txt
