# .github/workflows/test-artifact-upload.yml
name: Test Artifact

on: workflow_dispatch

jobs:
  test-artifact-upload:
    name: Test Artifact Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - run: mkdir -p ./artifacts/directory{1,2}

      - run: echo "This is a test file" > ./artifacts/directory1/test-file-1.txt

      - run: echo "This is another test file" > ./artifacts/directory2/test-file-2.txt

      - uses: actions/upload-artifact@v3
        with:
          name: test-artifact-1
          path: ./artifacts/directory1/test-file-1.txt

      - uses: actions/upload-artifact@v3
        with:
          name: test-artifact-2
          path: ./artifacts/directory2/test-file-2.txt

  test-artifact-download:
    name: Test Artifact Download
    runs-on: ubuntu-latest
    needs: test-artifact-upload
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: test-artifact-1
          path: artifacts

      - uses: actions/download-artifact@v3
        with:
          name: test-artifact-2
          path: artifacts

      - name: Display structure of downloaded files
        run: find ./artifacts -type f

      - name: Get checksums (SHA512) from artifacts
        run: find ./artifacts -type f -exec sha512sum {} \; | sed -e 's/ .*[/ ]/ /' > ./checksums.txt

      - uses: actions/upload-artifact@v3
        with:
          name: checksums
          path: ./checksums.txt
