# .github/workflows/test-artifact-upload.yml
name: Test Artifact

on: workflow_dispatch

jobs:
  test-artifact-upload:
    name: Test Artifact Upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - run: mkdir -p ./packages/app/packages

      - run: echo "This is a test file" > ./packages/app/packages/xxx-yyy-10.22.0.AppImage

      - run: echo "This is another test file" > ./packages/app/packages/xxx-yyy-10.22.0.dmg

      - run: echo "This is the last test file" > ./packages/app/packages/xxx-yyy-10.22.0.exe

      - uses: actions/upload-artifact@v3
        with:
          name: packaged-apps
          path: |
            packages/app/packages/*.dmg
            packages/app/packages/*.AppImage
            packages/app/packages/*.exe

  test-artifact-download:
    name: Test Artifact Download
    runs-on: ubuntu-latest
    needs: test-artifact-upload
    steps:
      - name: Checkout Git Repository
        uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: packaged-apps
          path: artifacts

      - name: Get checksums (SHA512) from artifacts
        run: find ./artifacts -type f -exec sha512sum {} \; | sed -e 's/ .*[/ ]/ /' > ./checksums.txt

      - uses: actions/upload-artifact@v3
        with:
          name: checksums
          path: ./checksums.txt
